### ISSUE TITLE
Lager Data fails to render if struct contains channel

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-golang/lager#11]
In go 1.5 the `http.Request` object now has a `Cancel` field of type `<-chan struct {}` which means a request can no longer be passed as `lager.Data{myRequest}` - it fails with: `json: unsupported type: <-chan struct {}`

It seems like we should ignore fields we cannot serialize, rather than failing? This feels like safer behavior

**Comment by fraenkel** [comment]
This is all core Go code. You would need to raise an issue with them. But it seems if you are blindly serializing objects, you will end in trouble. While it might be useful at times, there are many ways this won't work or might leak data you didn't expect.

**Comment by ematpl** [comment]
Hi, @robdimsdale,

We don't plan to make lager's serialization of `Data` values that sophisticated. Would it at least be helpful to warn clients in the README that they shouldn't include values in `lager.Data` that can't be serialized as JSON?

Thanks,
Eric

**Comment by robdimsdale** [comment]
@fraenkel @ematpl thanks for the explanation. I agree that blindly serializing objects is a bad idea, especially when those objects aren't under your control and may contain credentials (`http.Request` ticks both of those boxes).

If there was a quick fix to this codebase I would have been open to submitting a PR, but as you indicate the issue lies upstream, I don't think there is anything to be done here. I don't feel strongly about adding a warning to the documentation.
