### ISSUE TITLE
Debug logging does JSON marshaling regardless of whether debug logging is enabled

### ISSUE THREAD

**Issue by nelsam** [pivotal-golang/lager#17]
This presents serious performance problems in systems with noisy, json-heavy debug logs, but also applies to other log levels. JSON marshalling is also repeated for each sink. 

see https://github.com/pivotal-golang/lager/blob/master/logger.go#L89

**Comment by cwlbraa** [comment]
;)

**Comment by ematpl** [comment]
Good point, @nelsam and @cwlbraa. Would fixing this require a new `Sink`-like interface? The byte-slice in the [current `Sink` interface](https://github.com/pivotal-golang/lager/blob/master/writer_sink.go#L12-L15) implies some sort of serialization has to occur before each Sink can even decide whether it's going to emit the message.

Thanks,
Eric

**Comment by luan** [comment]
@nelsam, we made the changes, as a result we changed the `Sink` interface, that will break alternative Sink implementations if you have any, but if you're using lager's own `WriterSink` you should be good to go.
