### ISSUE TITLE
Timestamps as float64?

### ISSUE THREAD

**Issue by altenhof** [pivotal-golang/lager#19]
Hi there,

I was wondering whether there's any particular reason why lager is reporting timestamps as float64. We have seen setups where this can cause trouble: Using lager as the logging library for Go applications in Cloud Foundry and shipping those logs via firehose-to-syslog leads to an overall log message in JSON that has two fields named "timestamp", one with data type int64 and one with data type float64.

Processing such logs with ELK may lead to issues if the ES type mapping for "timestamp" is either explicitly set to "long" or if type mapping is done dynamically and the first log that enters ES has just one "timestamp" field (i.e. not written by lager).

So, would it cause any harm to switch to int64?

Thanks

Michael

**Comment by cwlbraa** [comment]
Hello @altenhof,

Thanks for the question. While the loggregator stack does use int64 nanoseconds for timestamps, lager chose to write its timestamps as epoch time in seconds. While it is less precise, we've never felt like there was anything to gain from nanosecond precision on its own. Seconds have the significant advantage of being more human-readable in our logs, as well as being a more standard cross-platform timestamp, as evidenced by the majority of timestamp converters on google, or the standard print formats of other languages (like cloud controller's ruby timestamps).

Loggregator's decision to use golang's UnixNano() call when writing the actual log lines is understandable, but is probably based on Golang's time library using nanosecond int64s as its standard, in-memory representation of time.  We'd rather not leak that implementation detail to the user. 

The clash of the two timestamps is certainly unfortunate, but moving away from the  standard unix timestamp format seems like the wrong approach for lager.

Thanks,
@cwlbraa && @jenspinney
CF Diego Engineers

**Comment by altenhof** [comment]
Hi @cwlbraa and @jenspinney,

thanks for your answer. I'm still not sure whether I fully got it and apologies for not being an expert on all timestamp formats and "standards" in this world. 

Given your statement that you  "write ... timestamps as epoch time in seconds" and the fact that I see lager logs with timestamps like this

```
"timestamp":"1464850044.012679100"
```

that lager writes timestamps as epoch time in seconds **including a fractional part with nano second resolution**. Correct?

I'm also a bit puzzled on the statement about using golang's UnixNano: Looking at [logger.currentTimestamp](https://github.com/pivotal-golang/lager/blob/master/logger.go#L178) it's used there, too, and the result that it produces is still leaking the implementation detail to the user, isn't it?
  
Thanks again

Michael

**Comment by jfmyers9** [comment]
Hi @altenhof,

Yes it is correct that lager writes timestamps as epoch time in seconds with fractional nano second resolution.

If we were to change the timestamp field in lager to an `int64`, this would result in one of two side effects:
- Our logs would be written in epoch time in seconds without fractional nano second resolution
- Our logs would be written with timestamps in nanosecond resolution

For usability reasons, I believe we are uncomfortable with either of these side effects as we want to maintain the nano second resolution, and we would like to keep our timestamps in the more common epoch time in seconds format. 

The point about loggregator using `time.UnixNano` is mainly related to the fact that the `int64` column in their structured log messages is in nanosecond resolution. It is true that we grab `time.UnixNano` in lager, however we convert it into our desired output format before writing the actual log line. 

I do believe that there is a larger conversation about the format of our timestamps being even more human readable and consumable, however I believe that change would take us even farther from using `int64` as the type of the timestamp column, and closer to using a `string` value.

Let me know if you have any other questions,

@jfmyers9, CF Diego Team

**Comment by altenhof** [comment]
Hi @jfmyers9,

thanks for your explanations.

As it turns out, `timestamp` is just one example, where formats may collide. We recently came across logs written by an app using lager that writes "errors" either as a simple string or a nested JSON object.
AFAIK, there is no easy way to make ElasticSearch accept both variants without further trouble ahead.
So I guess the only working solution for us is to detect and ignore (i.e. don't try to parse) log messages that don't fit into our schema.

Thanks again for explaining your point of view.

Michael

**Comment by ematpl** [comment]
Thanks, @altenhof. One point we may have missed in the above discussion is that you're using the [firehose-to-syslog utility](https://github.com/cloudfoundry-community/firehose-to-syslog) to translate loggregator messages to syslog, which directly translates the nanosecond-valued timestamp field from each log message envelope into the nanosecond-valued timestamp field in its JSON output. You could suggest that that utility instead convert the value into seconds (either integral or floating-point) before emitting it, so as to match existing conventions around [Unix epoch time](https://en.wikipedia.org/wiki/Unix_time). Given that the utility has been around for quite some time, though, its maintainers may not wish to adopt that presumably breaking change.

Thanks again,
Eric, CF Runtime Diego PM
